version: '2.1'

services:

  postgres_db:
    build:
      context: ./airflow_architecture/services/metadatabase
      dockerfile: Dockerfile
    image: postgres_db
    container_name: airflow_metadatabase
    ports:
      - "5432:5432"

  webserver:
    build:
      context: ./airflow_architecture/services/webserver
      dockerfile: Dockerfile
    image: airflow_webserver
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres_db
    volumes:
      - ./airflow_architecture/dags:/usr/local/airflow/dags
      - ./airflow_architecture/logs:/usr/local/airflow/logs
      - ./airflow_architecture/lib:/usr/local/airflow/lib
      - ./project_name_A:/usr/local/airflow/project_name_A
      - ./project_name_B:/usr/local/airflow/project_name_B
      - ./airflow_architecture/airflow.cfg:/usr/local/airflow/airflow.cfg
    entrypoint: ""
    ports:
      - "8080:8080"
    command: bash -c "airflow initdb && airflow webserver"

  scheduler:
    build:
      context: ./airflow_architecture/services/scheduler
      dockerfile: Dockerfile
    image: airflow_scheduler
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./airflow_architecture/dags:/usr/local/airflow/dags
      - ./airflow_architecture/logs:/usr/local/airflow/logs
      - ./airflow_architecture/lib:/usr/local/airflow/lib
      - ./project_name_A:/usr/local/airflow/project_name_A
      - ./project_name_B:/usr/local/airflow/project_name_B
      - ./airflow_architecture/airflow.cfg:/usr/local/airflow/airflow.cfg
    command: bash -c "airflow scheduler"

